import { useState } from "react";
import axios from "axios";

const apiKey = import.meta.env.VITE_OPENAI_API_KEY;

const Completion = () => {
  const [prompt, setPrompt] = useState("");
  const [imageUrl, setImageUrl] = useState("");

  const handleSubmit = async (e) => {
    e.preventDefault();
    setImageUrl("");
    try {
      const res = await axios.post(
        "https://api.openai.com/v1/images/generations",
        {
          model: "dall-e-3",
          prompt,
        },
        {
          headers: {
            Authorization: `Bearer ${apiKey}`,
            "Content-Type": "application/json",
          },
        },
      );

      const imageUrl = res.data.data[0].url;
      setImageUrl(imageUrl);
    } catch (error) {
      console.error("Error generating image with OpenAI:", error);
    }
  };

  return (
    <div>
      <form onSubmit={handleSubmit}>
        <label htmlFor="prompt">
          Ask a question to OpenAI (text 2 image):
          <input
            id="prompt"
            type="text"
            value={prompt}
            onChange={(e) => setPrompt(e.target.value)}
            onSubmit={handleSubmit}
          />
        </label>
      </form>
      {imageUrl && (
        <div>
          <img src={imageUrl} alt="Generated by OpenAI" />
        </div>
      )}
    </div>
  );
};

export default Completion;
